pkgname         = "store"
output          = "internal/infrastructure/store"
wipe            = true
no-tests        = true
add-enum-types  = true

[psql]
  dbname  = "app"
  host    = "localhost"
  port    = 5432
  user    = "postgres"
  pass    = "postgres"
  sslmode = "disable"
